wsk -i action delete synthetic
wsk -i action delete mobilenet
wsk -i action delete lr_review
wsk -i action delete video_process
wsk -i action delete pyaes
wsk -i action delete matmult
wsk -i action delete linpack
wsk -i action delete image_process
wsk -i action delete chameleon
wsk -i action delete hello