# The API Gateway is currently used to expose the Controller API
#   see apigateway/conf/whisk-docker-compose.conf
# Minio is used to mock an object storage ( i.e. S3) that hosts the api-gateway configuration.
# Minio also exposes a web UI to browse the files: http://localhost:9001/minio/api-gateway/
minio:
  image: minio/minio:RELEASE.2018-07-13T00-09-07Z
  command:
    - server
    - /data
  environment:
    - MINIO_ACCESS_KEY=zFE3frmjIeGtC-f_aimhUkn9ARiIm2HrkM1haFV4Mqw
    - MINIO_SECRET_KEY=756c222f96e27b3c85e8e703cf206fa900dce3e55ef32516bbed18136dbca23a
  volumes:
    - /data:/data:rw
  ports:
    - "9000:9011"